pipeline {
  agent any
  stages {
    stage('Build Application') {
      steps {
        sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
      }
      post {
        success {
          echo "We are archiving artifact"
          archiveArtifacts artifacts: '**/*.war', followSymlinks: false
        }
      }
     }
    stage('CreateTomcatImage') {
      steps {
        copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: lastSuccessful()
        echo "Building docker image"
        sh '''
        original_pwd=$(pwd -P)
        cd jenkins/java-tomcat-sample
        docker build -t localtomcatimg:$BUILD_NUMBER .
        cd $original_pwd
        sh '''
      }
     }
    stage('Deploy in QA instance'){
      steps {
        echo "We are deploying the app"
        sh '''
        docker container stop tomcatlocalinstance || true
        docker container rm tomcatlocalinstance || true
        docker container run -itd --name tomcatlocalinstance -p 8083:8080 localtomcatimg:$BUILD_NUMBER
        sh '''
      }
     }
     stage('Deploy in stagging instance'){
      steps {
        echo "We are deploying the app"
        sh '''
        docker container stop tomcatstagginginstance || true
        docker container rm tomcatstagginginstance || true
        docker container run -itd --name tomcatstagginginstance -p 8084:8080 localtomcatimg:$BUILD_NUMBER
        sh '''
      }
     }
   }
}
