pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Archive artifacts..."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Create Tomcat Image') {
           steps {
            copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
            echo "Buidling docker image"
            sh '''
            original_pwd=$(pwd -P)
            cd jenkins/java-tomcat-sample
            docker build -t localtomcatimg:$BUILD_NUMBER .
            sh '''
           } 
        }
        stage('Deploy to stagging') {
            steps {
                echo "Runnning in stagging env"
                sh '''
                docker container stop tomcatstagingenv || true
                docker container rm tomcatstagingenv || true
                docker run -itd --name tomcatstagingenv -p 8085:8080 localtomcatimg:$BUILD_NUMBER
                sh '''
            }
        }
        stage('Deploy to Prod') {
            steps {
                timeout(time:1, unit:'DAYS'){
                input message:'Approve PRODUCTION Deployment?'
                }
                echo "Runnning in Prod env"
                sh '''
                docker container stop tomcatprodenv || true
                docker container rm tomcatprodenv || true
                docker run -itd --name tomcatprodenv -p 8086:8080 localtomcatimg:$BUILD_NUMBER
                sh '''
            }
        }
    }
}
